
import { GeneticSample, ProteinStructure, TeamMember } from './types';

// 10 Realistic Genetic Sequence Examples with Protein Mapping and Bilingual Data
export const GENETIC_SAMPLES: GeneticSample[] = [
  {
    id: 'S001',
    filename: 'seq_cftr_exon10.fasta',
    patientId: 'PT-2024-089',
    geneTarget: 'CFTR',
    chromosome: '7',
    cytoband: 'q31.2',
    startPosition: 117559000,
    locus: 'Exon 10',
    uploadDate: '2024-05-12',
    sequence: 'ATGCAGAGGTCGCCTCTGGAAAAGGCCAGCGTTGTCTCCAAACTTTTTTTCAGCTGGACCAGACCAATTTTGAGGAAAGGATACAGACAGCGCCTGGAATTGTCAGACATATACCAAATCCCTTCTGTTGATTCTGCTGACAATCTATCTGAAAAATTGGAAAGAGAATGGGATAGAGAGCTGGCTTCAAAGAAAAATCCTAAACTCATTAATGCCCTTCGGCGATGTTTTTTCTGGAGATTTATGTTCTATGGAATCTTTTTATATTTAGGGGAAGTCACCAAAGCAGTACAGCCTCTCTTACTGGGAAGAATCATAGCTTCCTATGACCCGGATAACAAGGAGGAACGCTCTATCGCGATTTATCTAGGCATAGGCTTATGCCTTCTCTTTATTGTGAGGACACTGCTCCTACACCCAGCCATTTTTGGCCTTCATCACATTGGAATGCAGATGAGAATAGCTATGTTTAGTTTGATTTATAAGAAGACTTTAAAGCTGTCAAGCCGTGTTCTAGATAAAATAAGTATTGGACAACTTGTTAGTCTCCTTTCCAACAACCTGAACAAATTTGATGAAGGACTTGCATTGCACATTCTTCATGGTTTT',
    cdnaSequence: 'ATGCAGAGGTCGCCTCTGGAAAAGGCCAGCGTTGTCTCCAAACTTTTTTTCAGCTGGACCAGACCAATTTTGAGGAAAGGATACAGACAGCGCCTGGAATTGTCAGACATATACCAAATCCCTTCTGTTGATTCTGCTGACAATCTATCTGAAAAATTGGAAAGAGAATGGGATAGAGAGCTGGCTTCAAAGAAAAATCCTAAACTCATTAATGCCCTTCGGCGATGTTTTTTCTGGAGATTTATGTTCTATGGAATCTTTTTATATTTAGGGGAAGTCACCAAAGCAGTACAGCCTCTCTTACTGGGAAGAATCATAGCTTCCTATGACCCGGATAACAAGGAGGAACGCTCTATCGCGATTTATCTAGGCATAGGCTTATGCCTTCTCTTTATTGTGAGGACACTGCTCCTACACCCAGCCATTTTTGGCCTTCATCACATTGGAATGCAGATGAGAATAGCTATGTTTAGTTTGATTTATAAGAAGACTTTAAAGCTGTCAAGCCGTGTTCTAGATAAAATAAGTATTGGACAACTTGTTAGTCTCCTTTCCAACAACCTGAACAAATTTGATGAAGGACTTGCATTGCACATTCTTCATGGTTTT',
    proteinSequence: 'MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLEREWDRELASKKNPKLINLPRRCFFWRFMFYGIFLYLGEVTKAVQPLLLGRIIASYDPDNKEERSIAIYLGIGLCLLFIVRTLLLHPAIFGLHHIGMQMRIAMFSLIYKKTLKLSSRVLDKISIGQLVSLLSNNLNKFDEGLALHILHGF',
    mutations: [
      { 
        position: 152, // Index in sequence string
        ref: 'T', 
        alt: 'A', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'HIGH', 
        score: 98.5, 
        associatedDisease: 'Cystic Fibrosis',
        associatedDiseaseZh: '囊性纤维化',
        cdsChange: 'c.152T>A',
        aaChange: 'p.Phe51Ile'
      },
      { 
        position: 405, 
        ref: 'G', 
        alt: 'T', 
        type: 'Nonsense', 
        typeZh: '无义突变',
        impact: 'HIGH', 
        score: 99.1, 
        associatedDisease: 'Cystic Fibrosis',
        associatedDiseaseZh: '囊性纤维化',
        cdsChange: 'c.405G>T',
        aaChange: 'p.Trp135Ter'
      }
    ]
  },
  {
    id: 'S002',
    filename: 'seq_hbb_beta_globin.fasta',
    patientId: 'PT-2024-112',
    geneTarget: 'HBB',
    chromosome: '11',
    cytoband: 'p15.4',
    startPosition: 5225464,
    locus: 'Exon 1',
    uploadDate: '2024-05-14',
    sequence: 'ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGGTGAGTCTATGGGACCCTTGATGTTTTCTTTCCCCTTCTTTTCTATGGTTAAGTTCATGTCATAGGAAGGGGATAAGTAACAGGGTACAGTTTAGAATGGGAAACAGACGAATGATTGCATCAGTGTGGAAGTCTCAGGATCGTTTTAGTTTCTTTTATTTGCTGTTCATAACAATTGTTTTCTTTTGTTTAATTCTTGCTTTCTTTTTTTTTCTTCTCCGCAATTTTTACTATTATACTTAATGCCTTAACATTGTGTATAACAAAAGGAAATATCTCTGAGATACATTAAGTAACTTAAAAAAAAACTTTACACAGTCTGCCTAGTACATTACTATTTGGAATATATGTGTGCTTATTTGCATATTCATAATCTCCCTACTTTATTTTCTTTTATTTTTAATTGATACATAATCATTATACATATTTATGGGTTAAAGTGTAATGTTTTAATATGTGTACACATATTGACCAAATCAGGGTAATTTTGCATTTGTAATTTTAAAAAATGCTTTCTTCTTTTAATATACTTTTTTGTTTATCTTATTTCTAATACTTTCCCTAATCTCTTTCTTTCAGGGCAATAATGATACAATGTATCATGCCTCTTTGCACCATTCTAAAGAATAACAGTGATAATTTCTGGGTTAAGGCAATAGCAATATTTCTGCATATAAATATTTCTGCATATAAATTGTAACTGATGTAAGAGGTTTCATATTGCTAATAGCAGCTACAATCCAGCTACCATTCTGCTTTTATTTTATGGTTGGGATAAGGCTGGATTATTCTGAGTCCAAGCTAGGCCCTTTTGCTAATCATGTTCATACCTCTTATCTTCCTCCCACAGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCACTAAGCTCGCTTTCTTGCTGTCCAATTTCTATTAAAGGTTCCTTTGTC',
    cdnaSequence: 'ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGGTGAGTCTATGGGACCCTTGATGTTTTCTTTCCCCTTCTTTTCTATGGTTAAGTTCATGTCATAGGAAGGGGATAAGTAACAGGGTACAGTTTAGAATGGGAAACAGACGAATGATTGCATCAGTGTGGAAGTCTCAGGATCGTTTTAGTTTCTTTTATTTGCTGTTCATAACAATTGTTTTCTTTTGTTTAATTCTTGCTTTCTTTTTTTTTCTTCTCCGCAATTTTTACTATTATACTTAATGCCTTAACATTGTGTATAACAAAAGGAAATATCTCTGAGATACATTAAGTAACTTAAAAAAAAACTTTACACAGTCTGCCTAGTACATTACTATTTGGAATATATGTGTGCTTATTTGCATATTCATAATCTCCCTACTTTATTTTCTTTTATTTTTAATTGATACATAATCATTATACATATTTATGGGTTAAAGTGTAATGTTTTAATATGTGTACACATATTGACCAAATCAGGGTAATTTTGCATTTGTAATTTTAAAAAATGCTTTCTTCTTTTAATATACTTTTTTGTTTATCTTATTTCTAATACTTTCCCTAATCTCTTTCTTTCAGGGCAATAATGATACAATGTATCATGCCTCTTTGCACCATTCTAAAGAATAACAGTGATAATTTCTGGGTTAAGGCAATAGCAATATTTCTGCATATAAATATTTCTGCATATAAATTGTAACTGATGTAAGAGGTTTCATATTGCTAATAGCAGCTACAATCCAGCTACCATTCTGCTTTTATTTTATGGTTGGGATAAGGCTGGATTATTCTGAGTCCAAGCTAGGCCCTTTTGCTAATCATGTTCATACCTCTTATCTTCCTCCCACAGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCACTAAGCTCGCTTTCTTGCTGTCCAATTTCTATTAAAGGTTCCTTTGTC',
    proteinSequence: 'MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH',
    mutations: [
      { 
        position: 20, 
        ref: 'A', 
        alt: 'T', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'HIGH', 
        score: 95.2, 
        associatedDisease: 'Beta Thalassemia',
        associatedDiseaseZh: 'β-地中海贫血',
        cdsChange: 'c.20A>T',
        aaChange: 'p.Glu7Val'
      }
    ]
  },
  {
    id: 'S003',
    filename: 'seq_fbn1_marfan.vcf',
    patientId: 'PT-2024-156',
    geneTarget: 'FBN1',
    chromosome: '15',
    cytoband: 'q21.1',
    startPosition: 48700000,
    locus: 'Exon 24-25',
    uploadDate: '2024-05-18',
    sequence: 'ATGCGTCGAGGGCGTCTGCTGGAGATCGCCCTGGGATTTACCGTGCTTTTAGCGTCCTACACGAGCCATGGGGCGGACGCCAATTTGGAGGCTGGGAACGTGAAGGAAACCAGAGCCAGTCGGGCCAAGAGAAGAGGCGGTGGAGGACACGACGCGCTTAAAGGACCCAATGTCTGTGGATCACGTTATAATGCTTACTGTTGCCCTGGATGGAAAACCTTACCTGGCGGAAATCAGTGTATTGTCCCCATTTGCCAGAATTCAGGATGTTTGCGAGATGATCAATTTGATGGTACTGCTTCGTCTGTGTGAATGGATGTCTATGCAACGGTACCATCCTGTGAAATTCCACAACCAAACAGAGTCAGAATATAAGCAAAGACAAATTGTAGGAGAAAGTCAGTACAGCGGAGAAGATAGTTGGTGGAAGTCCTTGGAAGTAGGGAAAATACAGAAACAG',
    cdnaSequence: 'ATGCGTCGAGGGCGTCTGCTGGAGATCGCCCTGGGATTTACCGTGCTTTTAGCGTCCTACACGAGCCATGGGGCGGACGCCAATTTGGAGGCTGGGAACGTGAAGGAAACCAGAGCCAGTCGGGCCAAGAGAAGAGGCGGTGGAGGACACGACGCGCTTAAAGGACCCAATGTCTGTGGATCACGTTATAATGCTTACTGTTGCCCTGGATGGAAAACCTTACCTGGCGGAAATCAGTGTATTGTCCCCATTTGCCAGAATTCAGGATGTTTGCGAGATGATCAATTTGATGGTACTGCTTCGTCTGTGTGAATGGATGTCTATGCAACGGTACCATCCTGTGAAATTCCACAACCAAACAGAGTCAGAATATAAGCAAAGACAAATTGTAGGAGAAAGTCAGTACAGCGGAGAAGATAGTTGGTGGAAGTCCTTGGAAGTAGGGAAAATACAGAAACAG',
    proteinSequence: 'MRRGRLLEIALGFTVLLASYTSHGADANLEAGNVKETRASRAKRRGGGHDALKGPNVCGSRYNAYCCPGWKTYLAEISVLSPFAREQDVCE MINLMVLLRLCEWMSMQRYHPVKFHNQTESEYKQRQIVGESQYSGEDSWWKSLEVGKIQKQ',
    mutations: [
      { 
        position: 105, 
        ref: 'C', 
        alt: 'G', 
        type: 'Frameshift', 
        typeZh: '移码突变',
        impact: 'HIGH', 
        score: 99.8, 
        associatedDisease: 'Marfan Syndrome',
        associatedDiseaseZh: '马凡综合征',
        cdsChange: 'c.105C>G',
        aaChange: 'p.Pro35Argfs'
      },
      { 
        position: 210, 
        ref: 'T', 
        alt: 'C', 
        type: 'Synonymous', 
        typeZh: '同义突变',
        impact: 'LOW', 
        score: 12.5, 
        associatedDisease: 'None',
        associatedDiseaseZh: '无',
        cdsChange: 'c.210T>C',
        aaChange: 'p.Leu70='
      }
    ]
  },
  {
    id: 'S004',
    filename: 'seq_smn1_sma.fasta',
    patientId: 'PT-2024-201',
    geneTarget: 'SMN1',
    chromosome: '5',
    cytoband: 'q13.2',
    startPosition: 70247700,
    locus: 'Exon 7',
    uploadDate: '2024-05-20',
    sequence: 'ATGGCGATGAGCAGCGGCGGCAGTGGTGGCGGCGTCCCGGAGCAGGAGGATTCCGTGCTGTTCCGGCGCGGCACAGGCCAGAGCGATGATTCTGACATTTGGGATGATACAGCACTGATAAAAGCATATGATAAAGCTGTGGCTTCATTTAAGCATGCTCTAAAGAATGGTGACATTTGTGAAACTTCGGGTAAACCAAAAACCACACCTAAAAGAAAACCTGCTAAGAAGAATAAAAGCCAAAAGAAGAATACTGCAGCTTCCTTACAACAGTGGAAAGTTGGGGACAAATGTTCTGCCATTTGGTCAGAAGACGGTTGCATTTACCCAGCTACCATTGCTTCAATTGATTTTAAGAGAGAAACCTGTGTTGTGGTTTACACTGGATATGGAAATAGAGAGGAGCAAAATCTGTCCGATCTACTTTCCCCAATCTGTGAAGTAGCTAATAATATAGAACAGAATGCTCAAGAGAATGAAAATGAAAGCCAAGTTTCAACAGATGAAAGTGAGAACTCCAGGTCTCCTGGAAATAAATCAGATAACATCAAGCCCAAAATCTCC',
    cdnaSequence: 'ATGGCGATGAGCAGCGGCGGCAGTGGTGGCGGCGTCCCGGAGCAGGAGGATTCCGTGCTGTTCCGGCGCGGCACAGGCCAGAGCGATGATTCTGACATTTGGGATGATACAGCACTGATAAAAGCATATGATAAAGCTGTGGCTTCATTTAAGCATGCTCTAAAGAATGGTGACATTTGTGAAACTTCGGGTAAACCAAAAACCACACCTAAAAGAAAACCTGCTAAGAAGAATAAAAGCCAAAAGAAGAATACTGCAGCTTCCTTACAACAGTGGAAAGTTGGGGACAAATGTTCTGCCATTTGGTCAGAAGACGGTTGCATTTACCCAGCTACCATTGCTTCAATTGATTTTAAGAGAGAAACCTGTGTTGTGGTTTACACTGGATATGGAAATAGAGAGGAGCAAAATCTGTCCGATCTACTTTCCCCAATCTGTGAAGTAGCTAATAATATAGAACAGAATGCTCAAGAGAATGAAAATGAAAGCCAAGTTTCAACAGATGAAAGTGAGAACTCCAGGTCTCCTGGAAATAAATCAGATAACATCAAGCCCAAAATCTCC',
    proteinSequence: 'MAMSSGGSGGGVPEQEDSVLFRRGTGQSDDSDIWDDTALIKAYDKAVASFKHALKNGDICETSGKPKTTPKRKPAKKNKSQKKNTAASLQQWKVGDKCSAIWSEDGCIYPATIASIDFKRETCVVVYTGYGNREEQNLSDLLSPICEVANNIEQNAQENENESQVSTDESENSRSPGNKSDNIKPKIS',
    mutations: [
      { 
        position: 280, 
        ref: 'C', 
        alt: 'T', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'HIGH', 
        score: 94.4, 
        associatedDisease: 'Spinal Muscular Atrophy',
        associatedDiseaseZh: '脊髓性肌萎缩症',
        cdsChange: 'c.280C>T',
        aaChange: 'p.Arg94Cys'
      }
    ]
  },
  {
    id: 'S005',
    filename: 'seq_htt_huntington.txt',
    patientId: 'PT-2024-222',
    geneTarget: 'HTT',
    chromosome: '4',
    cytoband: 'p16.3',
    startPosition: 3076400,
    locus: 'Exon 1 (Poly-Q)',
    uploadDate: '2024-05-21',
    sequence: 'ATGGCGACCCTGGAAAAGCTGATGAAGGCCTTCGAGTCCCTCAAGTCCTTCCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCCGCCACCGCCGCCGCCGCCGCCGCCGCCTCCTCAGCTTCCTCAGCCGCCGCCGCAGGCACAGCCGCTGCTGCCTCAGCCGCAGCCGCCCCCGCCGCCGCCCCCGCCGCCACCCGGCCCGGCTGTGGCTGAGGAGCCGCTGCACCGACCAAAGAAAGAACTTTCAGCTACCCCAAGCCCTGAG',
    cdnaSequence: 'ATGGCGACCCTGGAAAAGCTGATGAAGGCCTTCGAGTCCCTCAAGTCCTTCCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCCGCCACCGCCGCCGCCGCCGCCGCCGCCTCCTCAGCTTCCTCAGCCGCCGCCGCAGGCACAGCCGCTGCTGCCTCAGCCGCAGCCGCCCCCGCCGCCGCCCCCGCCGCCACCCGGCCCGGCTGTGGCTGAGGAGCCGCTGCACCGACCAAAGAAAGAACTTTCAGCTACCCCAAGCCCTGAG',
    proteinSequence: 'MATLEKLMKAFESLKSFQQQQQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPPPQLPQPPPQAQPLLPQPQPPPPPPPPPPGPAVAEEPLHRPKKELSATPSPE',
    mutations: [
      { 
        position: 60, 
        ref: 'CAG', 
        alt: 'CAG...', 
        type: 'Expansion', 
        typeZh: '重复序列扩增',
        impact: 'HIGH', 
        score: 99.9, 
        associatedDisease: 'Huntington Disease',
        associatedDiseaseZh: '亨廷顿舞蹈症',
        cdsChange: 'c.60_90dup',
        aaChange: 'p.Gln20_Gln30dup'
      }
    ]
  },
  // --- NEW SAMPLES ---
  {
    id: 'S006',
    filename: 'seq_pah_pku.fasta',
    patientId: 'PT-2024-305',
    geneTarget: 'PAH',
    chromosome: '12',
    cytoband: 'q23.2',
    startPosition: 102838000,
    locus: 'Exon 12',
    uploadDate: '2024-05-23',
    sequence: 'ATGTCCACTGCGGTCCTGGAAAACCCAGGCTTGGGCAGGAACTACTTACCATTACTGTATACCTTGGTTACCTCATGTGGTGGTGCCTTGTATAGTTTGGAATTTCCTAATCCTCGTGGTCTCAGTTTTATGCGCTTTCCAGTGTGGTTTGTTGGAGAAAGATGTTTACATAGAGATGTGTATCATAGAGGGAGACTTCGAAGAGAACGGTTACAACCGTTGCTACCTCCTCTTGAAGGAATAAAGTAA',
    cdnaSequence: 'ATGTCCACTGCGGTCCTGGAAAACCCAGGCTTGGGCAGGAACTACTTACCATTACTGTATACCTTGGTTACCTCATGTGGTGGTGCCTTGTATAGTTTGGAATTTCCTAATCCTCGTGGTCTCAGTTTTATGCGCTTTCCAGTGTGGTTTGTTGGAGAAAGATGTTTACATAGAGATGTGTATCATAGAGGGAGACTTCGAAGAGAACGGTTACAACCGTTGCTACCTCCTCTTGAAGGAATAAAGTAA',
    proteinSequence: 'MSTAVLENPGLGRNYLPLLYTLDTSCGGALYSLEFPNPRGLSFMRFPVWFVGERCLHRDVYHRGRLRRERLQPLLPPLEGIK*',
    mutations: [
      { 
        position: 122, 
        ref: 'C', 
        alt: 'T', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'HIGH', 
        score: 96.1, 
        associatedDisease: 'Phenylketonuria (PKU)',
        associatedDiseaseZh: '苯丙酮尿症',
        cdsChange: 'c.122C>T',
        aaChange: 'p.Arg408Trp'
      }
    ]
  },
  {
    id: 'S007',
    filename: 'seq_dmd_dystrophin.vcf',
    patientId: 'PT-2024-340',
    geneTarget: 'DMD',
    chromosome: 'X',
    cytoband: 'p21.2',
    startPosition: 31137344,
    locus: 'Exon 44',
    uploadDate: '2024-05-24',
    sequence: 'ATGTTACTGGCTGGAAGAGTTTTAGAAAAACTGAATCCAAAAGCAATGGTTTTAATCAGAGCTGCGGCAAAAACTAAAGGTTCCAAAGAACTTGGAAAGGTTGGACAGTACTTAACAAAAAGTGAAACTGCAGATAGTGTGCTGGAGGCCTTGGAAAAACTGAAACATATTTCTTCTGAGGTTTCTGTACTGCAGGAAAAAGAGCAATTGCTTGGTGAACTAGAAGTAAAAGTAAATCAAAATAATAA',
    cdnaSequence: 'ATGTTACTGGCTGGAAGAGTTTTAGAAAAACTGAATCCAAAAGCAATGGTTTTAATCAGAGCTGCGGCAAAAACTAAAGGTTCCAAAGAACTTGGAAAGGTTGGACAGTACTTAACAAAAAGTGAAACTGCAGATAGTGTGCTGGAGGCCTTGGAAAAACTGAAACATATTTCTTCTGAGGTTTCTGTACTGCAGGAAAAAGAGCAATTGCTTGGTGAACTAGAAGTAAAAGTAAATCAAAATAATAA',
    proteinSequence: 'MLLAGRVLEKLNPKAMVLIRAAAKTKGSKELGKVGQYLTKSETADSVLEALEKLKHISSEVSVLQEKEQLLGELEVKVNQNN',
    mutations: [
      { 
        position: 45, 
        ref: 'T', 
        alt: '-', 
        type: 'Deletion', 
        typeZh: '缺失突变',
        impact: 'HIGH', 
        score: 99.5, 
        associatedDisease: 'Duchenne Muscular Dystrophy',
        associatedDiseaseZh: '杜氏肌营养不良',
        cdsChange: 'c.45delT',
        aaChange: 'p.Leu15fs'
      }
    ]
  },
  {
    id: 'S008',
    filename: 'seq_brca1_breast.fasta',
    patientId: 'PT-2024-410',
    geneTarget: 'BRCA1',
    chromosome: '17',
    cytoband: 'q21.31',
    startPosition: 43044295,
    locus: 'Exon 11',
    uploadDate: '2024-05-25',
    sequence: 'ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGTCAACTTGTTGAAGAGCTATTGAAAATCATTTGTGCTTTTCAGCTTGACACAGGTTTGGAGTATGCAAACAGCTATAATTTTGCAAAAAAGGAAAATAACTCTCCTGAACATCTAAAAGATGAAGTTTCTATCATCCAAAGTATGGGCTACAGAAACCGTGCCAAAAGACTTCTACAGAGTGAACCCGAAAATCCTTCCTTGCAGGAAACCAGTCTCAGTGTCCAACTCTCTAACCTTGGAACTGTGAGAACTCTGAGGACAAAGCAGCGGATACAACCTCAAAAGACGTCTGTCTACATTGAATTGGGATCTGATTCTTCTGAAGATACCGTTAATAAGGCAACTTATTGCAGTGTGGGAGATCAAGAATTGTTACAAATCACCCCTCAAGGAACCAGGGATGAAATCAGTTTGGATTCTGCAAAAAAGGCTGCTTGTGAATTTTCTGAGACGGATGTAACAAATACTGAACATCATCAACCCAGTAATAATGATTTGAACACCACTGAGAAGCGTGCAGCTGAGAGGCATCCAGAAAAGTATCAGGGTAGTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGGCTTAGCAAGGAGCCAACATAACAGATGGGCTGGAAGTAAGGAAACATGTAATGATAGGCGGACTCCCAGCACAGAAAAAAAGGTAGATCTGAATGCTGATCCCCTGTGTGAGAGAAAAGAATGGAATAAGCAGAAACTGCCATGCTCAGAGAATCCTAGAGATACTGAAGATGTTCCTTGGATAACACTAAATAGCAGCATTCAGAAAGTTAATGAGTGGTTTTCCAGAAGTGATGAACTGTTAGGTTCTGATGACTCACATGATGGGGAGTCTGAATCAAATGCCAAAGTAGCTGATGTATTGGACGTTCTAAATGAGGTAGATGAATATTCTGGTTCTTCAGAGAAAATAGACTTACTGGCCAGTGATCCTCATGAGGCTTTAATATGTAAAAAGTGAAAG',
    cdnaSequence: 'ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGTCAACTTGTTGAAGAGCTATTGAAAATCATTTGTGCTTTTCAGCTTGACACAGGTTTGGAGTATGCAAACAGCTATAATTTTGCAAAAAAGGAAAATAACTCTCCTGAACATCTAAAAGATGAAGTTTCTATCATCCAAAGTATGGGCTACAGAAACCGTGCCAAAAGACTTCTACAGAGTGAACCCGAAAATCCTTCCTTGCAGGAAACCAGTCTCAGTGTCCAACTCTCTAACCTTGGAACTGTGAGAACTCTGAGGACAAAGCAGCGGATACAACCTCAAAAGACGTCTGTCTACATTGAATTGGGATCTGATTCTTCTGAAGATACCGTTAATAAGGCAACTTATTGCAGTGTGGGAGATCAAGAATTGTTACAAATCACCCCTCAAGGAACCAGGGATGAAATCAGTTTGGATTCTGCAAAAAAGGCTGCTTGTGAATTTTCTGAGACGGATGTAACAAATACTGAACATCATCAACCCAGTAATAATGATTTGAACACCACTGAGAAGCGTGCAGCTGAGAGGCATCCAGAAAAGTATCAGGGTAGTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGGCTTAGCAAGGAGCCAACATAACAGATGGGCTGGAAGTAAGGAAACATGTAATGATAGGCGGACTCCCAGCACAGAAAAAAAGGTAGATCTGAATGCTGATCCCCTGTGTGAGAGAAAAGAATGGAATAAGCAGAAACTGCCATGCTCAGAGAATCCTAGAGATACTGAAGATGTTCCTTGGATAACACTAAATAGCAGCATTCAGAAAGTTAATGAGTGGTTTTCCAGAAGTGATGAACTGTTAGGTTCTGATGACTCACATGATGGGGAGTCTGAATCAAATGCCAAAGTAGCTGATGTATTGGACGTTCTAAATGAGGTAGATGAATATTCTGGTTCTTCAGAGAAAATAGACTTACTGGCCAGTGATCCTCATGAGGCTTTAATATGTAAAAAGTGAAAG',
    proteinSequence: 'MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQKKGPSQCPLCKNDITKRSLQESTRFSQLVEELLKIICAFQLDTGLEYANSYNFAKKENNSPEHLKDEVSIIQSMGYRNRAKRLLQSEPENPSLQETSLSVQLSNLGTVRTLRTKQRIQPQKTSVYIELGSDSSEDTVNKATYCSVGDQELLQITPQGTRDEISLDSAKKAACEFSETDVTNTEHHQPSNNDLNTTEKRAAERHPEKYQGSSVSNLHVEPCGTNTHASSLQHENSSLLLTKDRMNVEKAEFCNKSKQPGLARSQHNRWAGSKETCNDRRTPSTEKKVDLNADPLCERKEWNKQKLPCSENPRDTEDVPWITLNSSIQKVNEWFSRSDELLGSDDSHDGESESNAKVADVLDVLNEVDEYSGSSEKIDLLASDPHEALICKK*',
    mutations: [
      { 
        position: 185, 
        ref: 'AG', 
        alt: '-', 
        type: 'Deletion', 
        typeZh: '缺失突变',
        impact: 'HIGH', 
        score: 97.8, 
        associatedDisease: 'Breast Cancer Susceptibility',
        associatedDiseaseZh: '遗传性乳腺癌',
        cdsChange: 'c.185delAG',
        aaChange: 'p.Glu23fs'
      }
    ]
  },
  {
    id: 'S009',
    filename: 'seq_ldlr_fh.fasta',
    patientId: 'PT-2024-488',
    geneTarget: 'LDLR',
    chromosome: '19',
    cytoband: 'p13.2',
    startPosition: 11089360,
    locus: 'Exon 4',
    uploadDate: '2024-05-26',
    sequence: 'ATGGGGCCCTGGGGCTGGAAATTGCGCTGGACCCTGCGGCAGCAGTGTCCTGAGTACTGCAACTCTGGCCTGCTGCTGACCAACCTGCAGTGCCCAGACGGGATCGTGGACTTCTTCCGCGTGTGCGACCTGGACATCATCTTCCAGAGCGACCCCAACCTGCTGCCTCTGGAGGACGTCCAGGTCAATGTCACCTGCAGCGAGAACCAGTGGCAGTGCGAGCAGCACGTGTGCCACAACCACGCTCGCTACTACGTGGACATCTTGAGGATCTGA',
    cdnaSequence: 'ATGGGGCCCTGGGGCTGGAAATTGCGCTGGACCCTGCGGCAGCAGTGTCCTGAGTACTGCAACTCTGGCCTGCTGCTGACCAACCTGCAGTGCCCAGACGGGATCGTGGACTTCTTCCGCGTGTGCGACCTGGACATCATCTTCCAGAGCGACCCCAACCTGCTGCCTCTGGAGGACGTCCAGGTCAATGTCACCTGCAGCGAGAACCAGTGGCAGTGCGAGCAGCACGTGTGCCACAACCACGCTCGCTACTACGTGGACATCTTGAGGATCTGA',
    proteinSequence: 'MGPWGWKLRWTLRQQCPEYCNSGLLLTNLQCPDGIVDFFRVCDLDIIFQSDPNLLPLEDVQVNVTCSENQWQCEQHVCHNHARYYVDILRI*',
    mutations: [
      { 
        position: 81, 
        ref: 'G', 
        alt: 'A', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'MODERATE', 
        score: 88.3, 
        associatedDisease: 'Familial Hypercholesterolemia',
        associatedDiseaseZh: '家族性高胆固醇血症',
        cdsChange: 'c.81G>A',
        aaChange: 'p.Cys27Tyr'
      }
    ]
  },
  {
    id: 'S010',
    filename: 'seq_g6pd_def.fasta',
    patientId: 'PT-2024-512',
    geneTarget: 'G6PD',
    chromosome: 'X',
    cytoband: 'q28',
    startPosition: 154531000,
    locus: 'Exon 6',
    uploadDate: '2024-05-27',
    sequence: 'ATGTATGGCAATCGATTCGAAGGCGAGATCTTCATCTCCCTGGGCCTGTTTTCCGTGCCACCGGCGCTCACCCTGGAGCACATCAACGACAACCTGGAGAAGCGGGTCATCCTGGGCAAGATGGTGGGCCTGCCCAAGCAGCTGTTCACCCTGGGCACCCCCTTCGAGGGCCGCGAGGTCTTCGTCTTCCAGACGTACCTGGACGGCGGCGAGGAGCGGCGCCAGTTCACCTCGGTGCACGAGCTGCAGCTGGTGGAGTACGACCCCGTGGACACCAGCGCCAACGTCAAGGTGGTGTTCGGCGAGAAG',
    cdnaSequence: 'ATGTATGGCAATCGATTCGAAGGCGAGATCTTCATCTCCCTGGGCCTGTTTTCCGTGCCACCGGCGCTCACCCTGGAGCACATCAACGACAACCTGGAGAAGCGGGTCATCCTGGGCAAGATGGTGGGCCTGCCCAAGCAGCTGTTCACCCTGGGCACCCCCTTCGAGGGCCGCGAGGTCTTCGTCTTCCAGACGTACCTGGACGGCGGCGAGGAGCGGCGCCAGTTCACCTCGGTGCACGAGCTGCAGCTGGTGGAGTACGACCCCGTGGACACCAGCGCCAACGTCAAGGTGGTGTTCGGCGAGAAG',
    proteinSequence: 'MYGNRFEGEIFISLGLFSVPPALTLDHINDNLEKRVILGKMVGLPKQLFTLGTPFEGREVFVFQTYLDGGEERRQFTSVHELQLVEYDPVDTSANVKVVFGEK',
    mutations: [
      { 
        position: 202, 
        ref: 'G', 
        alt: 'A', 
        type: 'Missense', 
        typeZh: '错义突变',
        impact: 'MODERATE', 
        score: 85.0, 
        associatedDisease: 'G6PD Deficiency',
        associatedDiseaseZh: 'G6PD 缺乏症 (蚕豆病)',
        cdsChange: 'c.202G>A',
        aaChange: 'p.Val68Met'
      }
    ]
  }
];

// 10 Real-world Protein Structure Examples
export const PROTEIN_STRUCTURES: ProteinStructure[] = [
  {
    id: 'P001',
    pdbId: '1CRN',
    name: 'Crambin',
    nameZh: 'Crambin 蛋白',
    category: 'Plant Protein',
    categoryZh: '植物蛋白',
    molecularWeight: '4.7 kDa',
    resolution: '1.50 Å',
    chainCount: 1,
    description: 'Hydrophobic protein from Abyssinian cabbage seeds. Used as a model for protein folding.',
    descriptionZh: '来自阿比西尼亚卷心菜种子的疏水蛋白。常用作蛋白质折叠模型。'
  },
  {
    id: 'P002',
    pdbId: '1AKI',
    name: 'Lysozyme',
    nameZh: '溶菌酶',
    category: 'Enzyme',
    categoryZh: '酶',
    molecularWeight: '14.3 kDa',
    resolution: '1.50 Å',
    chainCount: 1,
    description: 'Antimicrobial enzyme produced by animals that forms part of the innate immune system.',
    descriptionZh: '动物产生的抗菌酶，是先天免疫系统的一部分。'
  },
  {
    id: 'P003',
    pdbId: '4HHB',
    name: 'Hemoglobin',
    nameZh: '血红蛋白',
    category: 'Transport',
    categoryZh: '运输蛋白',
    molecularWeight: '64.5 kDa',
    resolution: '1.74 Å',
    chainCount: 4,
    description: 'Oxygen-transport metalloprotein in red blood cells. Tetrameric structure.',
    descriptionZh: '红细胞中的氧运输金属蛋白。具有四聚体结构。'
  },
  {
    id: 'P004',
    pdbId: '3H8D',
    name: 'CFTR Domain',
    nameZh: 'CFTR 结构域',
    category: 'Membrane Protein',
    categoryZh: '膜蛋白',
    molecularWeight: '28.1 kDa',
    resolution: '2.20 Å',
    chainCount: 1,
    description: 'Nucleotide binding domain of Cystic Fibrosis Transmembrane Conductance Regulator.',
    descriptionZh: '囊性纤维化跨膜传导调节因子的核苷酸结合域。'
  },
  {
    id: 'P005',
    pdbId: '1UBQ',
    name: 'Ubiquitin',
    nameZh: '泛素',
    category: 'Regulatory',
    categoryZh: '调节蛋白',
    molecularWeight: '8.5 kDa',
    resolution: '1.80 Å',
    chainCount: 1,
    description: 'Small regulatory protein found in most tissues of eukaryotic organisms.',
    descriptionZh: '存在于大多数真核生物组织中的小型调节蛋白。'
  },
  {
    id: 'P006',
    pdbId: '2L7S',
    name: 'Zinc Finger',
    nameZh: '锌指蛋白',
    category: 'DNA Binding',
    categoryZh: 'DNA结合蛋白',
    molecularWeight: '3.2 kDa',
    resolution: 'NMR',
    chainCount: 1,
    description: 'Classical C2H2 zinc finger domain targeting DNA sequences.',
    descriptionZh: '经典的 C2H2 锌指结构域，靶向 DNA 序列。'
  },
  {
    id: 'P007',
    pdbId: '5X29',
    name: 'Cas9',
    nameZh: 'Cas9 蛋白',
    category: 'Gene Editing',
    categoryZh: '基因编辑',
    molecularWeight: '160 kDa',
    resolution: '2.50 Å',
    chainCount: 2,
    description: 'CRISPR-associated protein 9, an RNA-guided DNA endonuclease.',
    descriptionZh: 'CRISPR 相关蛋白 9，一种 RNA 引导的 DNA 核酸内切酶。'
  },
  {
    id: 'P008',
    pdbId: '1MBN',
    name: 'Myoglobin',
    nameZh: '肌红蛋白',
    category: 'Storage',
    categoryZh: '储存蛋白',
    molecularWeight: '17.8 kDa',
    resolution: '2.00 Å',
    chainCount: 1,
    description: 'Iron- and oxygen-binding protein found in the muscle tissue of vertebrates.',
    descriptionZh: '脊椎动物肌肉组织中发现的铁和氧结合蛋白。'
  },
  {
    id: 'P009',
    pdbId: '6VXX',
    name: 'SARS-CoV-2 Spike',
    nameZh: '新冠病毒刺突蛋白',
    category: 'Viral Protein',
    categoryZh: '病毒蛋白',
    molecularWeight: '140 kDa',
    resolution: '2.80 Å',
    chainCount: 3,
    description: 'Spike glycoprotein structure in closed conformation.',
    descriptionZh: '处于闭合构象的刺突糖蛋白结构。'
  },
  {
    id: 'P010',
    pdbId: '3PBL',
    name: 'GFP',
    nameZh: '绿色荧光蛋白',
    category: 'Fluorescent',
    categoryZh: '荧光蛋白',
    molecularWeight: '27 kDa',
    resolution: '1.90 Å',
    chainCount: 1,
    description: 'Green Fluorescent Protein from Aequorea victoria.',
    descriptionZh: '来自维多利亚多管发光水母的绿色荧光蛋白。'
  }
];

// Team Members based on Proposal
export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Li Ruixue',
    role: 'Project Leader',
    roleZh: '项目负责人',
    description: 'Class of 2024 AI School. Responsible for overall project planning and algorithm architecture.',
    descriptionZh: '人工智能学院 24 级。负责项目整体规划与核心算法架构设计。',
    isAdvisor: false
  },
  {
    name: 'Zhang Zijia',
    role: 'Advisor',
    roleZh: '指导教师',
    description: 'Expert in AI and Bioinformatics. Provides academic guidance and resource support.',
    descriptionZh: '人工智能与生物信息学专家。提供学术指导与科研资源支持。',
    isAdvisor: true
  },
  {
    name: 'Yang Ruhui',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Algorithm optimization and data processing.',
    descriptionZh: '负责算法优化与生物数据处理。',
    isAdvisor: false
  },
  {
    name: 'Nie Junlin',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Backend development and system architecture.',
    descriptionZh: '负责后端开发与系统架构搭建。',
    isAdvisor: false
  },
  {
    name: 'Hu Qi',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Frontend interaction and visualization.',
    descriptionZh: '负责前端交互设计与可视化开发。',
    isAdvisor: false
  },
  {
    name: 'Lu Qinyu',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Medical data analysis and testing.',
    descriptionZh: '负责医学数据分析与临床验证测试。',
    isAdvisor: false
  },
  {
    name: 'Zhu Rui',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Product design and market research.',
    descriptionZh: '负责产品设计与市场调研。',
    isAdvisor: false
  },
  {
    name: 'Jin Yulin',
    role: 'Core Member',
    roleZh: '核心成员',
    description: 'Operations and business development.',
    descriptionZh: '负责项目运营与商务拓展。',
    isAdvisor: false
  }
];
